apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwebapp
  namespace: team1
  labels:
    app: testwebapp
    team: team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwebapp
      team: team1
  template:
    metadata:
      labels:
        app: testwebapp
        team: team1
    spec:
      containers:
        - name: testwebapp
          image: ghcr.io/esenkus/testwebapp:latest
          ports:
            - containerPort: 8080