apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwebapp
  labels:
    app: testwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwebapp
  template:
    metadata:
      labels:
        app: testwebapp
    spec:
      containers:
        - name: testwebapp
          image: ghcr.io/esenkus/testwebapp:latest
          ports:
            - containerPort: 8080