apiVersion: v1
kind: Service
metadata:
  name: testwebapp
  namespace: team1
spec:
  selector:
    app: testwebapp
    team: team1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
  # will still use NodePort if LoadBalancer is not supported
  type: LoadBalancer