apiVersion: v1
kind: Service
metadata:
  name: testwebapp
  namespace: team1
spec:
  selector:
    app: testwebapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort